### ISSUE TITLE
Filtrowanie placówek po możliwości pobrania

### ISSUE THREAD

**Issue by Pawel-Urbanczyk** [printu/ElektronicznyNadawca#7]
Jest jakaś możliwość żeby za pomocą metody `$elektronicznyNadawca->getPlacowkiPocztowe()` otrzymać liste tylko placówek które mają opcje pobrania przy odbiorze osobistym w punkcie pocztowym ?

**Comment by krzaczek** [comment]
Prosze sprawdzic w dokumetnacji API ==> https://e-nadawca.poczta-polska.pl/download/en_webapi_v87_20230620.zip
